# Generated by Django 4.2.1 on 2023-05-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='imageUrl',
            field=models.URLField(default=''),
        ),
    ]
