# Generated by Django 4.2.1 on 2023-05-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coffee_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='tagline',
        ),
    ]
